export default {

  // APP
  MESSAGE: 'MESSAGE',
  ERR_MSG_RESET: 'ERR_MSG_RESET',


  // BUILDER
  ADD: 'ADD',
  REMOVE: 'REMOVE',
  SET_INGREDIENTS: 'SET_INGREDIENTS',
  SET_TOTAL_PRICE: 'SET_TOTAL_PRICE',

  // ORDER
  ORDER: 'ORDER',
  ORDER_ERROR: 'ORDER_ERROR',

  // AUTH
  SIGN_UP: 'SIGN_UP',
  LOG_IN: 'LOG_IN',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR',
  LOG_IN_ERROR: 'LOG_IN_ERROR',
  LOG_OUT: 'LOG_OUT',
  LOG_OUT_ERROR: 'LOG_OUT_ERROR'
}